/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Mantra {
  'id' : bigint,
  'categories' : Array<string>,
  'meaning' : string,
  'name' : string,
  'transliteration' : string,
  'language' : string,
  'benefits' : string,
  'deity' : string,
  'mantraText' : string,
}
export interface Pooja {
  'id' : bigint,
  'duration' : bigint,
  'name' : string,
  'requiredItems' : Array<string>,
  'occasion' : string,
  'significance' : string,
  'procedure' : Array<string>,
  'deity' : string,
}
export interface _SERVICE {
  'addMantra' : ActorMethod<
    [string, string, string, string, string, string, string, Array<string>],
    bigint
  >,
  'addPooja' : ActorMethod<
    [string, string, string, Array<string>, Array<string>, bigint, string],
    bigint
  >,
  'getAllMantras' : ActorMethod<[], Array<Mantra>>,
  'getAllPoojas' : ActorMethod<[], Array<Pooja>>,
  'getMantra' : ActorMethod<[bigint], Mantra>,
  'getMantrasByCategory' : ActorMethod<[string], Array<Mantra>>,
  'getPooja' : ActorMethod<[bigint], Pooja>,
  'getPoojasByOccasion' : ActorMethod<[string], Array<Pooja>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];