/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Mantra = IDL.Record({
  'id' : IDL.Nat,
  'categories' : IDL.Vec(IDL.Text),
  'meaning' : IDL.Text,
  'name' : IDL.Text,
  'transliteration' : IDL.Text,
  'language' : IDL.Text,
  'benefits' : IDL.Text,
  'deity' : IDL.Text,
  'mantraText' : IDL.Text,
});
export const Pooja = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'requiredItems' : IDL.Vec(IDL.Text),
  'occasion' : IDL.Text,
  'significance' : IDL.Text,
  'procedure' : IDL.Vec(IDL.Text),
  'deity' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMantra' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'addPooja' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'getAllMantras' : IDL.Func([], [IDL.Vec(Mantra)], ['query']),
  'getAllPoojas' : IDL.Func([], [IDL.Vec(Pooja)], ['query']),
  'getMantra' : IDL.Func([IDL.Nat], [Mantra], ['query']),
  'getMantrasByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Mantra)], ['query']),
  'getPooja' : IDL.Func([IDL.Nat], [Pooja], ['query']),
  'getPoojasByOccasion' : IDL.Func([IDL.Text], [IDL.Vec(Pooja)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Mantra = IDL.Record({
    'id' : IDL.Nat,
    'categories' : IDL.Vec(IDL.Text),
    'meaning' : IDL.Text,
    'name' : IDL.Text,
    'transliteration' : IDL.Text,
    'language' : IDL.Text,
    'benefits' : IDL.Text,
    'deity' : IDL.Text,
    'mantraText' : IDL.Text,
  });
  const Pooja = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'requiredItems' : IDL.Vec(IDL.Text),
    'occasion' : IDL.Text,
    'significance' : IDL.Text,
    'procedure' : IDL.Vec(IDL.Text),
    'deity' : IDL.Text,
  });
  
  return IDL.Service({
    'addMantra' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'addPooja' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllMantras' : IDL.Func([], [IDL.Vec(Mantra)], ['query']),
    'getAllPoojas' : IDL.Func([], [IDL.Vec(Pooja)], ['query']),
    'getMantra' : IDL.Func([IDL.Nat], [Mantra], ['query']),
    'getMantrasByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Mantra)], ['query']),
    'getPooja' : IDL.Func([IDL.Nat], [Pooja], ['query']),
    'getPoojasByOccasion' : IDL.Func([IDL.Text], [IDL.Vec(Pooja)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };