/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Mantra {
    id: bigint;
    categories: Array<string>;
    meaning: string;
    name: string;
    transliteration: string;
    language: string;
    benefits: string;
    deity: string;
    mantraText: string;
}
export interface Pooja {
    id: bigint;
    duration: bigint;
    name: string;
    requiredItems: Array<string>;
    occasion: string;
    significance: string;
    procedure: Array<string>;
    deity: string;
}
export interface backendInterface {
    addMantra(name: string, deity: string, language: string, mantraText: string, transliteration: string, meaning: string, benefits: string, categories: Array<string>): Promise<bigint>;
    addPooja(name: string, deity: string, occasion: string, requiredItems: Array<string>, procedure: Array<string>, duration: bigint, significance: string): Promise<bigint>;
    getAllMantras(): Promise<Array<Mantra>>;
    getAllPoojas(): Promise<Array<Pooja>>;
    getMantra(id: bigint): Promise<Mantra>;
    getMantrasByCategory(category: string): Promise<Array<Mantra>>;
    getPooja(id: bigint): Promise<Pooja>;
    getPoojasByOccasion(occasion: string): Promise<Array<Pooja>>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMantra(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMantra(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMantra(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addPooja(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: Array<string>, arg5: bigint, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPooja(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPooja(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async getAllMantras(): Promise<Array<Mantra>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMantras();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMantras();
            return result;
        }
    }
    async getAllPoojas(): Promise<Array<Pooja>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPoojas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPoojas();
            return result;
        }
    }
    async getMantra(arg0: bigint): Promise<Mantra> {
        if (this.processError) {
            try {
                const result = await this.actor.getMantra(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMantra(arg0);
            return result;
        }
    }
    async getMantrasByCategory(arg0: string): Promise<Array<Mantra>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMantrasByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMantrasByCategory(arg0);
            return result;
        }
    }
    async getPooja(arg0: bigint): Promise<Pooja> {
        if (this.processError) {
            try {
                const result = await this.actor.getPooja(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPooja(arg0);
            return result;
        }
    }
    async getPoojasByOccasion(arg0: string): Promise<Array<Pooja>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoojasByOccasion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoojasByOccasion(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
